travis:
  secure:
    BINSTAR_TOKEN: ajKd4llJrwT9a1Q8x7cldEzIMAdpvhdmY1c2+1lrgkmYsU+wv5bKHqzIV0yKDaidIZShnrh9ooJlXBJU6/TGrHIWFofirXUMSjS+YUJH2zL9bTamlh0rUK6DXV0sO6GuiQl9i12bqb1zMUyYvhcYCsSGTbNVJvpFA+cD1+xZx0ZTry4qJOwgFRQ5T1J0Otl7zughmnskqBj5CZQuvILtHSWibSbyKj5/i6z4t9whc2RKdhYDaR4/UHLaI4vKnbj4cZ+i5Fr28wejL688hr/iPrmlZjn4KGC05h/7muRYSZn6Y1L0n5tZeKGhvFfqbi6TjeoNu0QMC/QoeiK3TG6YAE/3/WQZxoZtnXvDZh2EZBbQq4fzcxAbd9ADVF6IRUO8eyCi7j9xIHFbEeBeU4UBaIQnEV5Yt295WUSegIT80uwpFMxwK50d9gyL/z+cyUxgKTqlXDg3d8m7xAz+7ERa+8nuwQbcEK17Tc/o17igGACXcGJn9ydyXplNc38sqazWgvAYbqXndqKAz7pqIB5ZkIw1cpwyGScUnhMe7h2PHee0I4I9MC5YyomSrkQph2vgh1fBWkWqJNCom738hXfL98FAefiMOPMGy3pMsgp6OxyOF+/paTgn1sW/Eq+xmm6/udHmOpQicjnD465dUKcJgSmnQFItBSiUn5m17tpXkIs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
