travis:
  secure:
    BINSTAR_TOKEN: mr/CDz8BYAx3iPicVu0MuOCLh6jXKLqKdrEssfJocNPa0XtEzGumQJf4kou5A7JTUhjYx4Ih5eg6pXBRFaJgYYS7XMv1cwq67L05H2Zl2aMiaY9wpWHWC1COFUCPmXZ51jpZ65visAMwoh3uPkxjG+UVdd1drMWJB83qNBYq4bsLE+47/Iq3NCj8PBbdY3l8flxqLomiMeyZEIPY6D6inpC7ZGqa/skgN1+2/HZWbJkZZcR+RKxaNuFXhDCl8SZh6stFx7asOBorgW6SfNnZdXr/zdWnY/sEfYylsa+tmz64r+C1NnEjRp9aZgaTNP4igjS1478HDpT1HuQxmMjpSEOwu7tbd/6znPU175tA7z1RhdHsa9s07d18dOOgSTgjTDF4uVMzo3ISzomsgXTpFI32i7c79i9j4WYT+3iJ9d2VAX1CaB4AsyCLvIvXf4WB16l66AO0zPn5CMLeJVKx4mHSZUODRV/1jX3epVx/+4KAtw0/o2DMBkFRoZ4rRAewKAQk/2cUa33aC3kdqdN1nBSLRyyrFu4mAXRJV6wZv070hsR/wEgG2QtyDA6Hb5aRIsgM5Eq/wqouEqQkLAXqoKVYTyHWFrJdvnvEIAA07jBApVMi80RsWubNbNKmno3CRaJkbnRI+nQHSfiKyM5ObPS3OZnON5c4MuxVyAvFJFk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
