travis:
  secure:
    BINSTAR_TOKEN: LbxDwDtwDBJFZMXh9UCXoMuDUTgQ/AejOquwX2ElG3iRSQUl6X/Zy1/IFSphgYa9OcilFjn2Mowdi4JBluYWG8Tlr97lu0bUs3XOfFVEkBrYHTNox7Jbp+ysuezJmqQoqAczcQz3vc4TkOcHz4ZCmxWc1ZpGQEmGlO3tAIXxpEQtmQHLDf0ZSmKjiJLorwi/JGBKhord7Mi8sct5Lf7FclrltnxLV8TQoPwi3h2jHVG45nYssgab1S4/yNl9b3oDNSjNev9V35r99UvfMuphO3ih1fBT6xrDBgPFiF1vzlBDI+XTq6U1FMxuCiqw3YJjp1Z/BgZzdrjgBHlWdjC12hWEym53VkO85WH+HBwZcMCRFz2Bq3YO+A4Mvw/cSO1fpo8i5e/XQqlZf/LfgH2zK/bEGVY+3PXufVMJEk+qU8zUZqzEa2ibmwAYE1yTxz2gwulmkLjgkmJv6pOT3QUhhQLR/EnB0DPklXw3yJ811lDDkePJOrGzNEa2LlmGHpJFyzXjDxaFErqE/yYxXLG9M6R0IXkjjdmWptO8lB7KQoZRy5+G40UvYVmEMslgBYbMCXK6+EO8kR0WqSaJiBYa14zqA3DifdBSzSh7537dvJIUQyqs+IiJ54KAIaqY2Z9IkdHyroOY996rer5igwirGtG/dtXXjFF52uRIwYB5a2I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
